---
name: telescope.nvim
description: |
    Find, Filter, Preview, Pick. All lua, all the time.
homepage: https://github.com/nvim-telescope/telescope.nvim
languages: []
categories: []
licenses:
    - MIT

source:
    # renovate:datasource=github-refs
    id: pkg:github/nvim-telescope/telescope.nvim@415af52339215926d705cccc08145f3782c4d132
    archive:
        type: zipball

opt:
    pack/mason/opt/telescope.nvim/: "./"
