---
name: oil.nvim
description: |
    Neovim file explorer: edit your filesystem like a buffer
homepage: https://github.com/stevearc/oil.nvim
languages: []
categories: []
licenses:
    - MIT

source:
    # renovate:datasource=github-tags
    id: pkg:github/stevearc/oil.nvim@v2.14.0
    archive:
        type: zipball

opt:
    pack/mason/opt/oil.nvim/: "./"
