---
name: oil.nvim
homepage: https://github.com/stevearc/oil.nvim
description: "Neovim file explorer: edit your filesystem like a buffer"
languages: []
categories: []
licenses:
  - MIT

source:
  # renovate:datasource=github-tags
  id: pkg:generic/stevearc/oil.nvim@v2.14.0
  download:
    files:
      plugin.zip: https://github.com/stevearc/oil.nvim/archive/refs/tags/{{ version }}.zip
    artifact: oil.nvim-{{version | strip_prefix "v" }}/

opt:
  pack/mason/opt/oil.nvim/: "{{source.download.artifact}}"
