---
name: vim-unimpaired
description: |
    unimpaired.vim: Pairs of handy bracket mappings
homepage: https://github.com/tpope/vim-unimpaired
languages: []
categories: []
licenses:
    - proprietary

source:
    # renovate:datasource=github-refs
    id: pkg:github/tpope/vim-unimpaired@6d44a6dc2ec34607c41ec78acf81657248580bf1
    archive:
        type: zipball

opt:
    pack/mason/opt/vim-unimpaired/: "./"
