---
name: glance.nvim
homepage: https://github.com/DNLHC/glance.nvim
description: Peek preview window for LSP locations in Neovim
languages: []
categories: []
licenses:
  - MIT

source:
  # renovate:datasource=github-refs
  id: pkg:generic/DNLHC/glance.nvim@cf91734f28fcd35bd60a5a87b6d768faafb73268
  download:
    files:
      plugin.zip: https://github.com/DNLHC/glance.nvim/archive/{{ version }}.zip
    artifact: glance.nvim-{{ version }}/

opt:
  pack/mason/opt/glance.nvim/: "{{source.download.artifact}}"
