---
name: glance.nvim
description: |
    Peek preview window for LSP locations in Neovim
homepage: https://github.com/DNLHC/glance.nvim
languages: []
categories: []
licenses:
    - MIT

source:
    # renovate:datasource=github-refs
    id: pkg:github/DNLHC/glance.nvim@1a08824835d7582457b67acbe23ca33487912a5e
    archive:
        type: zipball

opt:
    pack/mason/opt/glance.nvim/: "./"
