---
name: vim-surround
homepage: https://github.com/tpope/vim-surround
description: "surround.vim: Delete/change/add parentheses/quotes/XML-tags/much more with ease"
languages: []
categories: []
licenses:
  - proprietary

source:
  # renovate:datasource=github-tags
  id: pkg:generic/tpope/vim-surround@v2.2
  download:
    files:
      plugin.zip: https://github.com/tpope/vim-surround/archive/refs/tags/{{ version }}.zip
    artifact: vim-surround-{{version | strip_prefix "v" }}/

opt:
  pack/mason/opt/vim-surround/: "{{source.download.artifact}}"
