---
name: vim-surround
description: |
    surround.vim: Delete/change/add parentheses/quotes/XML-tags/much more with ease
homepage: https://github.com/tpope/vim-surround
languages: []
categories: []
licenses:
    - proprietary

source:
    # renovate:datasource=github-refs
    id: pkg:github/tpope/vim-surround@3d188ed2113431cf8dac77be61b842acb64433d9
    archive:
        type: zipball

opt:
    pack/mason/opt/vim-surround/: "./"
